import type { EquipmentId } from '@/lib/programGenerator';

export type LibraryExercise = {
  id: string;
  name: string;
  muscleGroup: 'Chest' | 'Back' | 'Legs' | 'Shoulders' | 'Arms' | 'Core';
  equipment: EquipmentId;
  weightIncrement: number;
  defaultSets?: number;
  defaultRepRange?: string;
  defaultWeight?: number;
};

export const EXERCISE_LIBRARY: LibraryExercise[] = [
  // Chest
  {
    id: 'lib-bench-press',
    name: 'Barbell Bench Press',
    muscleGroup: 'Chest',
    equipment: 'barbell',
    weightIncrement: 2.5,
    defaultSets: 3,
    defaultRepRange: '8-10',
    defaultWeight: 60,
  },
  {
    id: 'lib-incline-db-press',
    name: 'Incline Dumbbell Press',
    muscleGroup: 'Chest',
    equipment: 'dumbbells',
    weightIncrement: 1,
    defaultSets: 3,
    defaultRepRange: '8-12',
    defaultWeight: 20,
  },
  {
    id: 'lib-db-bench-press',
    name: 'Dumbbell Bench Press',
    muscleGroup: 'Chest',
    equipment: 'dumbbells',
    weightIncrement: 1,
    defaultSets: 3,
    defaultRepRange: '8-12',
    defaultWeight: 22,
  },
  {
    id: 'lib-incline-barbell-press',
    name: 'Incline Barbell Bench Press',
    muscleGroup: 'Chest',
    equipment: 'barbell',
    weightIncrement: 2.5,
    defaultSets: 3,
    defaultRepRange: '8-10',
    defaultWeight: 50,
  },
  {
    id: 'lib-cable-fly',
    name: 'Cable Chest Fly',
    muscleGroup: 'Chest',
    equipment: 'machines',
    weightIncrement: 2.5,
    defaultSets: 3,
    defaultRepRange: '12-15',
    defaultWeight: 12.5,
  },
  {
    id: 'lib-push-ups',
    name: 'Push-ups',
    muscleGroup: 'Chest',
    equipment: 'bodyweight',
    weightIncrement: 0,
    defaultSets: 3,
    defaultRepRange: '12-20',
    defaultWeight: 0,
  },
  {
    id: 'lib-machine-chest-press',
    name: 'Machine Chest Press',
    muscleGroup: 'Chest',
    equipment: 'machines',
    weightIncrement: 5,
    defaultSets: 3,
    defaultRepRange: '10-12',
    defaultWeight: 45,
  },

  // Back
  {
    id: 'lib-deadlift',
    name: 'Conventional Deadlift',
    muscleGroup: 'Back',
    equipment: 'barbell',
    weightIncrement: 2.5,
    defaultSets: 3,
    defaultRepRange: '5',
    defaultWeight: 80,
  },
  {
    id: 'lib-barbell-row',
    name: 'Barbell Bent-Over Row',
    muscleGroup: 'Back',
    equipment: 'barbell',
    weightIncrement: 2.5,
    defaultSets: 3,
    defaultRepRange: '8-10',
    defaultWeight: 50,
  },
  {
    id: 'lib-pull-ups',
    name: 'Pull-ups',
    muscleGroup: 'Back',
    equipment: 'bodyweight',
    weightIncrement: 0,
    defaultSets: 3,
    defaultRepRange: '6-10',
    defaultWeight: 0,
  },
  {
    id: 'lib-lat-pulldown',
    name: 'Lat Pulldown',
    muscleGroup: 'Back',
    equipment: 'machines',
    weightIncrement: 2.5,
    defaultSets: 3,
    defaultRepRange: '10-12',
    defaultWeight: 50,
  },
  {
    id: 'lib-seated-cable-row',
    name: 'Seated Cable Row',
    muscleGroup: 'Back',
    equipment: 'machines',
    weightIncrement: 2.5,
    defaultSets: 3,
    defaultRepRange: '10-12',
    defaultWeight: 45,
  },
  {
    id: 'lib-single-arm-db-row',
    name: 'Single-Arm Dumbbell Row',
    muscleGroup: 'Back',
    equipment: 'dumbbells',
    weightIncrement: 1,
    defaultSets: 3,
    defaultRepRange: '10-12',
    defaultWeight: 22,
  },
  {
    id: 'lib-t-bar-row',
    name: 'T-Bar Row',
    muscleGroup: 'Back',
    equipment: 'barbell',
    weightIncrement: 2.5,
    defaultSets: 3,
    defaultRepRange: '8-10',
    defaultWeight: 40,
  },

  // Legs
  {
    id: 'lib-squat',
    name: 'Barbell Back Squat',
    muscleGroup: 'Legs',
    equipment: 'barbell',
    weightIncrement: 2.5,
    defaultSets: 3,
    defaultRepRange: '6-8',
    defaultWeight: 70,
  },
  {
    id: 'lib-front-squat',
    name: 'Barbell Front Squat',
    muscleGroup: 'Legs',
    equipment: 'barbell',
    weightIncrement: 2.5,
    defaultSets: 3,
    defaultRepRange: '6-8',
    defaultWeight: 50,
  },
  {
    id: 'lib-romanian-deadlift',
    name: 'Romanian Deadlift',
    muscleGroup: 'Legs',
    equipment: 'barbell',
    weightIncrement: 2.5,
    defaultSets: 3,
    defaultRepRange: '8-10',
    defaultWeight: 60,
  },
  {
    id: 'lib-leg-press',
    name: 'Leg Press',
    muscleGroup: 'Legs',
    equipment: 'machines',
    weightIncrement: 5,
    defaultSets: 3,
    defaultRepRange: '10-12',
    defaultWeight: 120,
  },
  {
    id: 'lib-bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    muscleGroup: 'Legs',
    equipment: 'dumbbells',
    weightIncrement: 1,
    defaultSets: 3,
    defaultRepRange: '10-12',
    defaultWeight: 14,
  },
  {
    id: 'lib-leg-extension',
    name: 'Leg Extension',
    muscleGroup: 'Legs',
    equipment: 'machines',
    weightIncrement: 2.5,
    defaultSets: 3,
    defaultRepRange: '12-15',
    defaultWeight: 40,
  },
  {
    id: 'lib-leg-curl',
    name: 'Lying Leg Curl',
    muscleGroup: 'Legs',
    equipment: 'machines',
    weightIncrement: 2.5,
    defaultSets: 3,
    defaultRepRange: '10-12',
    defaultWeight: 35,
  },
  {
    id: 'lib-standing-calf-raise',
    name: 'Standing Calf Raise',
    muscleGroup: 'Legs',
    equipment: 'machines',
    weightIncrement: 2.5,
    defaultSets: 4,
    defaultRepRange: '12-15',
    defaultWeight: 50,
  },
  {
    id: 'lib-walking-lunge',
    name: 'Walking Dumbbell Lunge',
    muscleGroup: 'Legs',
    equipment: 'dumbbells',
    weightIncrement: 1,
    defaultSets: 3,
    defaultRepRange: '10-12',
    defaultWeight: 12,
  },

  // Shoulders
  {
    id: 'lib-overhead-press',
    name: 'Overhead Barbell Press',
    muscleGroup: 'Shoulders',
    equipment: 'barbell',
    weightIncrement: 2.5,
    defaultSets: 3,
    defaultRepRange: '6-8',
    defaultWeight: 40,
  },
  {
    id: 'lib-db-shoulder-press',
    name: 'Standing Dumbbell Shoulder Press',
    muscleGroup: 'Shoulders',
    equipment: 'dumbbells',
    weightIncrement: 1,
    defaultSets: 3,
    defaultRepRange: '8-12',
    defaultWeight: 16,
  },
  {
    id: 'lib-lateral-raise',
    name: 'Dumbbell Lateral Raise',
    muscleGroup: 'Shoulders',
    equipment: 'dumbbells',
    weightIncrement: 1,
    defaultSets: 4,
    defaultRepRange: '12-15',
    defaultWeight: 8,
  },
  {
    id: 'lib-cable-lateral-raise',
    name: 'Cable Lateral Raise',
    muscleGroup: 'Shoulders',
    equipment: 'machines',
    weightIncrement: 1.25,
    defaultSets: 3,
    defaultRepRange: '12-15',
    defaultWeight: 5,
  },
  {
    id: 'lib-face-pull',
    name: 'Face Pulls',
    muscleGroup: 'Shoulders',
    equipment: 'machines',
    weightIncrement: 2.5,
    defaultSets: 3,
    defaultRepRange: '12-15',
    defaultWeight: 20,
  },
  {
    id: 'lib-reverse-pec-deck',
    name: 'Reverse Pec Deck',
    muscleGroup: 'Shoulders',
    equipment: 'machines',
    weightIncrement: 2.5,
    defaultSets: 3,
    defaultRepRange: '12-15',
    defaultWeight: 25,
  },

  // Arms
  {
    id: 'lib-barbell-curl',
    name: 'Barbell Bicep Curl',
    muscleGroup: 'Arms',
    equipment: 'barbell',
    weightIncrement: 2.5,
    defaultSets: 3,
    defaultRepRange: '8-10',
    defaultWeight: 25,
  },
  {
    id: 'lib-hammer-curl',
    name: 'Dumbbell Hammer Curl',
    muscleGroup: 'Arms',
    equipment: 'dumbbells',
    weightIncrement: 1,
    defaultSets: 3,
    defaultRepRange: '10-12',
    defaultWeight: 12,
  },
  {
    id: 'lib-incline-db-curl',
    name: 'Incline Dumbbell Bicep Curl',
    muscleGroup: 'Arms',
    equipment: 'dumbbells',
    weightIncrement: 1,
    defaultSets: 3,
    defaultRepRange: '10-12',
    defaultWeight: 10,
  },
  {
    id: 'lib-tricep-rope-pushdown',
    name: 'Cable Tricep Rope Pushdown',
    muscleGroup: 'Arms',
    equipment: 'machines',
    weightIncrement: 2.5,
    defaultSets: 3,
    defaultRepRange: '10-12',
    defaultWeight: 20,
  },
  {
    id: 'lib-skull-crushers',
    name: 'Skull Crushers',
    muscleGroup: 'Arms',
    equipment: 'barbell',
    weightIncrement: 2.5,
    defaultSets: 3,
    defaultRepRange: '8-10',
    defaultWeight: 25,
  },
  {
    id: 'lib-dips',
    name: 'Tricep Dips',
    muscleGroup: 'Arms',
    equipment: 'bodyweight',
    weightIncrement: 0,
    defaultSets: 3,
    defaultRepRange: '8-12',
    defaultWeight: 0,
  },

  // Core
  {
    id: 'lib-hanging-leg-raise',
    name: 'Hanging Leg Raise',
    muscleGroup: 'Core',
    equipment: 'bodyweight',
    weightIncrement: 0,
    defaultSets: 3,
    defaultRepRange: '10-15',
    defaultWeight: 0,
  },
  {
    id: 'lib-cable-crunch',
    name: 'Cable Crunch',
    muscleGroup: 'Core',
    equipment: 'machines',
    weightIncrement: 2.5,
    defaultSets: 3,
    defaultRepRange: '12-15',
    defaultWeight: 25,
  },
  {
    id: 'lib-plank',
    name: 'Plank',
    muscleGroup: 'Core',
    equipment: 'bodyweight',
    weightIncrement: 0,
    defaultSets: 3,
    defaultRepRange: '60s',
    defaultWeight: 0,
  },
  {
    id: 'lib-ab-wheel',
    name: 'Ab Wheel Rollout',
    muscleGroup: 'Core',
    equipment: 'bodyweight',
    weightIncrement: 0,
    defaultSets: 3,
    defaultRepRange: '8-12',
    defaultWeight: 0,
  },
];

