import type { EquipmentId } from './programGenerator';

export interface CatalogExercise {
  id: string;
  name: string;
  muscleGroup: string;
  equipment: EquipmentId;
  defaultWeight: number;
  targetRepRange: string;
  sets: number;
}

export const EXERCISE_CATALOG: CatalogExercise[] = [
  // Chest
  {
    id: 'barbell_bench_press',
    name: 'Barbell Bench Press',
    muscleGroup: 'Chest',
    equipment: 'barbell',
    defaultWeight: 60,
    targetRepRange: '6-10',
    sets: 3,
  },
  {
    id: 'incline_dumbbell_press',
    name: 'Incline Dumbbell Press',
    muscleGroup: 'Chest',
    equipment: 'dumbbells',
    defaultWeight: 22,
    targetRepRange: '8-12',
    sets: 3,
  },
  {
    id: 'dumbbell_bench_press',
    name: 'Dumbbell Bench Press',
    muscleGroup: 'Chest',
    equipment: 'dumbbells',
    defaultWeight: 24,
    targetRepRange: '8-12',
    sets: 3,
  },
  {
    id: 'incline_barbell_press',
    name: 'Incline Barbell Press',
    muscleGroup: 'Chest',
    equipment: 'barbell',
    defaultWeight: 50,
    targetRepRange: '6-10',
    sets: 3,
  },
  {
    id: 'cable_chest_fly',
    name: 'Cable Chest Fly',
    muscleGroup: 'Chest',
    equipment: 'machines',
    defaultWeight: 15,
    targetRepRange: '10-15',
    sets: 3,
  },
  {
    id: 'push_ups',
    name: 'Push-ups',
    muscleGroup: 'Chest',
    equipment: 'bodyweight',
    defaultWeight: 0,
    targetRepRange: '12-20',
    sets: 3,
  },
  {
    id: 'dips',
    name: 'Chest Dips',
    muscleGroup: 'Chest',
    equipment: 'bodyweight',
    defaultWeight: 0,
    targetRepRange: '8-12',
    sets: 3,
  },

  // Back
  {
    id: 'lat_pulldown',
    name: 'Lat Pulldown',
    muscleGroup: 'Back',
    equipment: 'machines',
    defaultWeight: 50,
    targetRepRange: '8-12',
    sets: 3,
  },
  {
    id: 'barbell_row',
    name: 'Barbell Bent-Over Row',
    muscleGroup: 'Back',
    equipment: 'barbell',
    defaultWeight: 55,
    targetRepRange: '6-10',
    sets: 3,
  },
  {
    id: 'seated_cable_row',
    name: 'Seated Cable Row',
    muscleGroup: 'Back',
    equipment: 'machines',
    defaultWeight: 45,
    targetRepRange: '8-12',
    sets: 3,
  },
  {
    id: 'dumbbell_row',
    name: 'Single-Arm Dumbbell Row',
    muscleGroup: 'Back',
    equipment: 'dumbbells',
    defaultWeight: 22,
    targetRepRange: '8-12',
    sets: 3,
  },
  {
    id: 'pull_ups',
    name: 'Pull-ups',
    muscleGroup: 'Back',
    equipment: 'bodyweight',
    defaultWeight: 0,
    targetRepRange: '6-10',
    sets: 3,
  },
  {
    id: 'face_pulls',
    name: 'Face Pulls',
    muscleGroup: 'Back',
    equipment: 'machines',
    defaultWeight: 25,
    targetRepRange: '12-15',
    sets: 3,
  },

  // Shoulders
  {
    id: 'overhead_press',
    name: 'Overhead Barbell Press',
    muscleGroup: 'Shoulders',
    equipment: 'barbell',
    defaultWeight: 40,
    targetRepRange: '6-10',
    sets: 3,
  },
  {
    id: 'dumbbell_shoulder_press',
    name: 'Dumbbell Shoulder Press',
    muscleGroup: 'Shoulders',
    equipment: 'dumbbells',
    defaultWeight: 18,
    targetRepRange: '8-12',
    sets: 3,
  },
  {
    id: 'lateral_raises',
    name: 'Lateral Dumbbell Raises',
    muscleGroup: 'Shoulders',
    equipment: 'dumbbells',
    defaultWeight: 10,
    targetRepRange: '12-15',
    sets: 3,
  },
  {
    id: 'cable_lateral_raise',
    name: 'Cable Lateral Raise',
    muscleGroup: 'Shoulders',
    equipment: 'machines',
    defaultWeight: 8,
    targetRepRange: '12-15',
    sets: 3,
  },

  // Legs (Quads, Hams, Glutes)
  {
    id: 'barbell_squat',
    name: 'Barbell Back Squat',
    muscleGroup: 'Legs',
    equipment: 'barbell',
    defaultWeight: 70,
    targetRepRange: '6-10',
    sets: 3,
  },
  {
    id: 'romanian_deadlift',
    name: 'Romanian Deadlift',
    muscleGroup: 'Legs',
    equipment: 'barbell',
    defaultWeight: 60,
    targetRepRange: '8-12',
    sets: 3,
  },
  {
    id: 'leg_press',
    name: 'Leg Press',
    muscleGroup: 'Legs',
    equipment: 'machines',
    defaultWeight: 120,
    targetRepRange: '8-12',
    sets: 3,
  },
  {
    id: 'bulgarian_split_squat',
    name: 'Bulgarian Split Squat',
    muscleGroup: 'Legs',
    equipment: 'dumbbells',
    defaultWeight: 16,
    targetRepRange: '8-12',
    sets: 3,
  },
  {
    id: 'leg_extension',
    name: 'Leg Extension',
    muscleGroup: 'Legs',
    equipment: 'machines',
    defaultWeight: 40,
    targetRepRange: '10-15',
    sets: 3,
  },
  {
    id: 'lying_leg_curl',
    name: 'Lying Leg Curl',
    muscleGroup: 'Legs',
    equipment: 'machines',
    defaultWeight: 35,
    targetRepRange: '10-15',
    sets: 3,
  },
  {
    id: 'walking_lunges',
    name: 'Walking Lunges',
    muscleGroup: 'Legs',
    equipment: 'dumbbells',
    defaultWeight: 16,
    targetRepRange: '10-12',
    sets: 3,
  },

  // Arms (Biceps & Triceps)
  {
    id: 'barbell_biceps_curl',
    name: 'Barbell Biceps Curl',
    muscleGroup: 'Arms',
    equipment: 'barbell',
    defaultWeight: 25,
    targetRepRange: '8-12',
    sets: 3,
  },
  {
    id: 'incline_dumbbell_curl',
    name: 'Incline Dumbbell Curl',
    muscleGroup: 'Arms',
    equipment: 'dumbbells',
    defaultWeight: 12,
    targetRepRange: '10-12',
    sets: 3,
  },
  {
    id: 'hammer_curl',
    name: 'Hammer Curl',
    muscleGroup: 'Arms',
    equipment: 'dumbbells',
    defaultWeight: 14,
    targetRepRange: '8-12',
    sets: 3,
  },
  {
    id: 'triceps_pushdown',
    name: 'Triceps Cable Pushdown',
    muscleGroup: 'Arms',
    equipment: 'machines',
    defaultWeight: 35,
    targetRepRange: '10-15',
    sets: 3,
  },
  {
    id: 'overhead_triceps_extension',
    name: 'Overhead Triceps Extension',
    muscleGroup: 'Arms',
    equipment: 'dumbbells',
    defaultWeight: 18,
    targetRepRange: '10-12',
    sets: 3,
  },
  {
    id: 'skull_crushers',
    name: 'EZ-Bar Skull Crushers',
    muscleGroup: 'Arms',
    equipment: 'barbell',
    defaultWeight: 25,
    targetRepRange: '8-12',
    sets: 3,
  },

  // Calves & Core
  {
    id: 'standing_calf_raise',
    name: 'Standing Calf Raise',
    muscleGroup: 'Calves',
    equipment: 'machines',
    defaultWeight: 40,
    targetRepRange: '12-15',
    sets: 3,
  },
  {
    id: 'hanging_knee_raise',
    name: 'Hanging Knee Raise',
    muscleGroup: 'Core',
    equipment: 'bodyweight',
    defaultWeight: 0,
    targetRepRange: '12-15',
    sets: 3,
  },
  {
    id: 'cable_crunch',
    name: 'Cable Kneeling Crunch',
    muscleGroup: 'Core',
    equipment: 'machines',
    defaultWeight: 35,
    targetRepRange: '12-15',
    sets: 3,
  },
  {
    id: 'plank',
    name: 'Weighted Plank',
    muscleGroup: 'Core',
    equipment: 'bodyweight',
    defaultWeight: 0,
    targetRepRange: '45-60 sec',
    sets: 3,
  },
];

