import { router } from 'expo-router';
import { useEffect, useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { ProgressBar } from '@/components/ui/ProgressBar';
import { Screen } from '@/components/ui/Screen';
import { colors } from '@/constants/colors';
import { spacing } from '@/constants/spacing';
import { generateProgram, type GeneratedProgram } from '@/lib/programGenerator';
import { defaultOnboarding, loadOnboarding } from '@/store/workoutStore';

export default function Home() {
	const [name, setName] = useState(defaultOnboarding.name);
	const [program, setProgram] = useState<GeneratedProgram>(() => generateProgram(defaultOnboarding));

	useEffect(() => { loadOnboarding().then((data) => { const onboarding = data ?? defaultOnboarding; setName(onboarding.name); setProgram(generateProgram(onboarding)); }); }, []);

	const workout = program.workouts[0];
	const recommendedExercise = workout.exercises[0];
	return <Screen><View style={styles.header}><View><Text style={styles.greeting}>Good evening, {name}</Text><Text style={styles.sub}>Monday, September 14</Text></View><View style={styles.avatar}><Text style={styles.avatarText}>{name.charAt(0).toUpperCase()}</Text></View></View><Card style={styles.readiness}><View style={styles.readinessTop}><View><Text style={styles.label}>TRAINING READINESS</Text><Text style={styles.ready}>Your body is ready</Text></View><Text style={styles.score}>94%</Text></View><ProgressBar value={94} /><Text style={styles.readinessHint}>Based on your recent training and recovery.</Text></Card><View style={styles.sectionRow}><Text style={styles.section}>TODAY'S WORKOUT</Text><Text style={styles.count}>01 / {program.daysPerWeek}</Text></View><Card style={styles.workout}><View style={styles.workoutTop}><View><Text style={styles.workoutName}>{workout.name}</Text><Text style={styles.focus}>{workout.muscleGroups.join(' • ')}</Text></View><Text style={styles.play}>▶</Text></View><View style={styles.details}><Text style={styles.detail}>{workout.exercises.length} exercises</Text><Text style={styles.detail}>~{workout.estimatedMinutes} min</Text></View><Button onPress={() => router.push({ pathname: '/workout/preview', params: { workoutId: workout.id } })}>START WORKOUT</Button></Card><View style={styles.sectionRow}><Text style={styles.section}>THIS WEEK</Text><Text style={styles.count}>0 / {program.daysPerWeek} WORKOUTS</Text></View><ProgressBar value={0} /><Card style={styles.insight}><Text style={styles.insightLabel}>SPOT INSIGHT</Text><Text style={styles.insightTitle}>{recommendedExercise.name} is ready for {recommendedExercise.recommendedWeight || 'bodyweight'}.</Text><Text style={styles.insightBody}>Based on your current generated plan.</Text></Card></Screen>;
}
const styles = StyleSheet.create({ header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: spacing.xl }, greeting: { color: colors.text, fontSize: 24, fontWeight: '800' }, sub: { color: colors.secondary, marginTop: 5 }, avatar: { backgroundColor: colors.primary, width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: colors.background, fontWeight: '900', fontSize: 18 }, readiness: { backgroundColor: colors.elevated, marginBottom: spacing.xxl }, readinessTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: spacing.lg }, label: { color: colors.secondary, fontSize: 11, letterSpacing: 1.1, fontWeight: '800' }, ready: { color: colors.text, fontSize: 18, fontWeight: '800', marginTop: 8 }, score: { color: colors.primary, fontSize: 36, fontWeight: '900' }, readinessHint: { color: colors.muted, fontSize: 12, marginTop: spacing.md }, sectionRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: spacing.md }, section: { color: colors.secondary, fontSize: 11, letterSpacing: 1.3, fontWeight: '800' }, count: { color: colors.muted, fontSize: 11, fontWeight: '800' }, workout: { marginBottom: spacing.xl }, workoutTop: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: spacing.xl }, workoutName: { color: colors.text, fontSize: 28, fontWeight: '800' }, focus: { color: colors.secondary, marginTop: 6 }, play: { color: colors.primary, fontSize: 22 }, details: { flexDirection: 'row', gap: spacing.xl, marginBottom: spacing.lg }, detail: { color: colors.secondary, fontSize: 13 }, insight: { borderColor: '#3A2C75', marginTop: spacing.lg, backgroundColor: '#181622' }, insightLabel: { color: colors.purple, fontSize: 11, fontWeight: '900', letterSpacing: 1.2 }, insightTitle: { color: colors.text, fontSize: 17, lineHeight: 24, fontWeight: '800', marginTop: spacing.md }, insightBody: { color: colors.secondary, fontSize: 13, marginTop: spacing.sm } });
